name: Deploy mdbook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install mdbook
        run: |-
          cargo install mdbook
          cargo install mdbook-toc
      - name: Update ADR indexes
        run: |-
          npx adr-log -i $(cat .adr-dir)/_index.md -d $(cat .adr-dir) -e _index.md
      - name: Build mdbook
        run: |-
          mdbook build
