name: Validate PR
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-changelog:
    uses: powerd6/.github/.github/workflows/mdbook-ci.yml@main
    secrets: inherit